import { RawDB } from '../../raw-db/models/raw-db'
import { FinalDB } from '../models/final-db'

export function computeDBFamily(
  db: RawDB.DBCharacter[],
): Record<number, FinalDB.CharacterFamily> {
  const result: Record<number, FinalDB.CharacterFamily> = {}
  const families: [string, FinalDB.CharacterFamily][] = []

  for (const [id, { family }] of db) {
    if (!family.length) {
      result[id] = {
        id: families.length,
        characters: [],
      }

      families.push(['', result[id]])

      continue
    }

    const key = family.join('|')

    const f = families.find(([k, fam]) => k === key)

    if (f) {
      result[id] = f[1]
      continue
    }

    result[id] = {
      id: families.length,
      characters: family.map(f => ({ key: f, aliases: familiesAliases[f] })),
    }

    families.push([key, result[id]])
  }

  return result
}

export const familiesAliases: Record<RawDB.Family, string[]> = {
  MonkeyDLuffy: ['Monkey D. Luffy'],
  RoronoaZoro: ['Roronoa Zoro'],
  Nami: ['Nami'],
  Usopp: ['Usopp'],
  VinsmokeSanji: ['Vinsmoke Sanji'],
  TonyTonyChopper: ['Tony Tony Chopper'],
  Higuma: ['Higuma'],
  MasterOfTheNearSea: ['Master of the Near Sea'],
  Alvida: ['Alvida'],
  Coby: ['Coby'],
  Helmeppo: ['Helmeppo'],
  Morgan: ['Morgan'],
  Mohji: ['Mohji'],
  Richie: ['Richie'],
  Cabaji: ['Cabaji'],
  Buggy: ['Buggy'],
  Gaimon: ['Gaimon'],
  Siam: ['Siam'],
  Butchie: ['Butchie'],
  Django: ['Django'],
  Kuro: ['Kuro'],
  Yosaku: ['Yosaku'],
  Johnny: ['Johnny'],
  Fullbody: ['Fullbody'],
  Patty: ['Patty'],
  Carne: ['Carne'],
  Zeff: ['Zeff'],
  Gin: ['Gin'],
  Pearl: ['Pearl'],
  Krieg: ['Krieg'],
  Nezumi: ['Nezumi'],
  Momoo: ['Momoo'],
  Choo: ['Choo'],
  Kuroobi: ['Kuroobi'],
  Hatchan: ['Hatchan', 'Hachi'],
  Arlong: ['Arlong'],
  Tashigi: ['Tashigi'],
  Smoker: ['Smoker'],
  NefertariVivi: ['Nefertari Vivi'],
  Karoo: ['Karoo'],
  PortgasDAce: ['Portgas D. Ace'],
  Shanks: ['Shanks'],
  SwordBandit: ['Sword Bandit'],
  PistolBandit: ['Pistol Bandit'],
  FighterGroupCrewPirates: ['Fighter Group Crew Pirates'],
  SlasherGroupCrewPirates: ['Slasher Group Crew Pirates'],
  StrikerGroupCrewPirates: ['Striker Group Crew Pirates'],
  ShooterGroupCrewPirates: ['Shooter Group Crew Pirates'],
  Cannoneer: ['Cannoneer'],
  Bodyguard: ['Bodyguard'],
  BlackCatPirates: ['Black Cat Pirates'],
  FighterGroupLeader: ['Fighter Group Leader'],
  SlasherGroupLeader: ['Slasher Group Leader'],
  StrikerGroupLeader: ['Striker Group Leader'],
  ShooterGroupLeader: ['Shooter Group Leader'],
  AssassinMaster: ['Assassin Master'],
  ArlongCrewmember: ['Arlong Crewmember'],
  KnuckleNavy: ['Knuckle Navy'],
  SaberNavy: ['Saber Navy'],
  HalberdNavy: ['Halberd Navy'],
  PistolNavy: ['Pistol Navy'],
  CannoneerNavy: ['Cannoneer Navy'],
  Gem: ['Gem', 'Mr. 5'],
  Mikita: ['Mikita', 'Miss Valentine'],
  Galdino: ['Galdino', 'Mr. 3'],
  Marianne: ['Marianne', 'Miss Goldenweek'],
  Bentham: ['Bentham', 'Mr. 2 Bon Clay', 'Bonclay'],
  NicoRobin: ['Nico Robin'],
  Mr9: ['Mr. 9'],
  Laboon: ['Laboon'],
  NeptunianSquid: ['Neptunian Squid'],
  DraculeMihawk: ['Dracule Mihawk'],
  Hina: ['Hina'],
  Igaram: ['Igaram', 'Mr. 8'],
  MissMonday: ['Miss Monday'],
  KnuckleBaroqueWorks: ['Knuckle Baroque Works'],
  SaberBaroqueWorks: ['Saber Baroque Works'],
  HalberdBaroqueWorks: ['Halberd Baroque Works'],
  PistolBaroqueWorks: ['Pistol Baroque Works'],
  BazookaBaroqueWorks: ['Bazooka Baroque Works'],
  Marco: ['Marco'],
  Jozu: ['Jozu'],
  Vista: ['Vista'],
  Izo: ['Izo'],
  Blamenco: ['Blamenco'],
  EdwardNewgate: ['Edward Newgate', 'Whitebeard'],
  Mr13: ['Mr. 13'],
  Dorry: ['Dorry'],
  Broggy: ['Broggy'],
  Triceratops: ['Triceratops'],
  Rex: ['Rex'],
  Brontosaurus: ['Brontosaurus'],
  Tsuru: ['Tsuru'],
  Momonga: ['Momonga'],
  Onigumo: ['Onigumo'],
  MonkeyDGarp: ['Monkey D. Garp'],
  TrafalgarDWaterLaw: ['Trafalgar D. Water Law'],
  BasilHawkins: ['Basil Hawkins'],
  Killer: ['Killer'],
  Urouge: ['Urouge'],
  Bepo: ['Bepo'],
  Kalifa: ['Kalifa'],
  Paulie: ['Paulie'],
  RobLucci: ['Rob Lucci'],
  Kaku: ['Kaku'],
  PeeplyLulu: ['Peeply Lulu'],
  Wapol: ['Wapol'],
  Dalton: ['Dalton'],
  Chessmarimo: ['Chessmarimo'],
  Kureha: ['Kureha', 'Doctorine'],
  Lapin: ['Lapin'],
  Franky: ['Franky', 'Cutty Flam'],
  Kiwi: ['Kiwi'],
  Mozu: ['Mozu'],
  Surume: ['Surume'],
  Zephyr: ['Zephyr'],
  Ain: ['Ain'],
  EustassKid: ['Eustass Kid'],
  ScratchmenApoo: ['Scratchmen Apoo'],
  XDrake: ['X Drake'],
  JewelryBonney: ['Jewelry Bonney'],
  CaponeBege: ['Capone Bege'],
  SilversRayleigh: ['Silvers Rayleigh'],
  GiantRedPirates: ['Giant Red Pirates'],
  GiantBluePirates: ['Giant Blue Pirates'],
  GiantGreenPirates: ['Giant Green Pirates'],
  GiantYellowPirates: ['Giant Yellow Pirates'],
  GiantBlackPirates: ['Giant Black Pirates'],
  SeaCat: ['Sea Cat'],
  Dugong: ['Dugong'],
  BananaGator: ['Banana Gator'],
  SandoraDragon: ['Sandora Dragon'],
  Crocodile: ['Crocodile', 'Mr. 0'],
  Hogback: ['Hogback'],
  VictoriaCindry: ['Victoria Cindry'],
  EmporioIvankov: ['Emporio Ivankov'],
  Perona: ['Perona'],
  Kumacy: ['Kumacy'],
  Inuppe: ['Inuppe'],
  Drophy: ['Drophy', 'Miss Merry Christmas'],
  Babe: ['Babe', 'Mr. 4'],
  Zala: ['Zala', 'Miss Doublefinger'],
  DazBones: ['Daz Bones', 'Mr. 1'],
  Rebecca: ['Rebecca'],
  Absalom: ['Absalom'],
  GeneralZombie: ['General Zombie'],
  Jigoro: ['Jigoro'],
  Jinbe: ['Jinbe', 'Jinbei', 'Jimbei'],
  BartholomewKuma: ['Bartholomew Kuma'],
  GeckoMoria: ['Gecko Moria'],
  BoaHancock: ['Boa Hancock'],
  DonquixoteDoflamingo: ['Donquixote Doflamingo'],
  Brook: ['Brook'],
  ShimotsukiRyuma: ['Shimotsuki Ryuma'],
  Masira: ['Masira'],
  Shoujou: ['Shoujou'],
  MontblancCricket: ['Montblanc Cricket'],
  SouthBirdForestResidents: ['South Bird & Forest Residents'],
  Bellamy: ['Bellamy'],
  Sarquiss: ['Sarquiss'],
  Elizabeth: ['Elizabeth'],
  Caroline: ['Caroline'],
  Cowboy: ['Cowboy'],
  BourbonJr: ['Bourbon Jr.'],
  Stomp: ['Stomp'],
  IvanX: ['Ivan X'],
  Centaur: ['Centaur'],
  Hikoichi: ['Hikoichi'],
  MarshallDTeach: ['Marshall D. Teach', 'Blackbeard'],
  Thatch: ['Thatch'],
  Namule: ['Namule'],
  Rakuyo: ['Rakuyo'],
  Fossa: ['Fossa'],
  Curiel: ['Curiel'],
  Sengoku: ['Sengoku'],
  Satori: ['Satori'],
  Shura: ['Shura'],
  Gedatsu: ['Gedatsu'],
  Braham: ['Braham'],
  Yama: ['Yama'],
  YellowSkypieaGuard: ['Yellow Skypiea Guard'],
  BlackSkypieaGuard: ['Black Skypiea Guard'],
  RedSkypieaGuardEnforcer: ['Red Skypiea Guard Enforcer'],
  BlueSkypieaGuardEnforcer: ['Blue Skypiea Guard Enforcer'],
  GreenSkypieaGuardEnforcer: ['Green Skypiea Guard Enforcer'],
  YellowSkypieaGuardEnforcer: ['Yellow Skypiea Guard Enforcer'],
  BlackSkypieaGuardEnforcer: ['Black Skypiea Guard Enforcer'],
  RedSkypieaEnforcer: ['Red Skypiea Enforcer'],
  BlueSkypieaEnforcer: ['Blue Skypiea Enforcer'],
  GreenSkypieaEnforcer: ['Green Skypiea Enforcer'],
  YellowSkypieaEnforcer: ['Yellow Skypiea Enforcer'],
  BlackSkypieaEnforcer: ['Black Skypiea Enforcer'],
  RedShandianWarrior: ['Red Shandian Warrior'],
  BlueShandianWarrior: ['Blue Shandian Warrior'],
  GreenShandianWarrior: ['Green Shandian Warrior'],
  YellowShandianWarrior: ['Yellow Shandian Warrior'],
  BlackShandianWarrior: ['Black Shandian Warrior'],
  Bellmere: ['Bellmere'],
  Kaya: ['Kaya'],
  Hotori: ['Hotori'],
  Kotori: ['Kotori'],
  Pell: ['Pell'],
  Chaka: ['Chaka'],
  Sabo: ['Sabo'],
  Heraclesn: ["Heracles'n"],
  Domino: ['Domino'],
  Minorhinoceros: ['Minorhinoceros'],
  Basilisk: ['Basilisk'],
  Ohm: ['Ohm'],
  NolaGiantSnake: ['Nola Giant Snake'],
  Wyper: ['Wyper'],
  Enel: ['Enel', 'Eneru'],
  Sadie: ['Sadie'],
  Minokoala: ['Minokoala'],
  Manticore: ['Manticore'],
  Porche: ['Porche'],
  Capote: ['Capote'],
  Hamburg: ['Hamburg'],
  Pickles: ['Pickles'],
  BigBun: ['Big Bun'],
  Foxy: ['Foxy'],
  Kuzan: ['Kuzan', 'Aokiji'],
  Genbou: ['Genbou'],
  Kamakiri: ['Kamakiri'],
  Raki: ['Raki'],
  Aisa: ['Aisa'],
  Nojiko: ['Nojiko'],
  Crocus: ['Crocus'],
  Koza: ['Koza'],
  HikingBear: ['Hiking Bear'],
  Purinpurin: ['Purinpurin'],
  Zanbai: ['Zanbai'],
  SuperhumanDestroyers: ['Superhuman Destroyers'],
  StreetPunkBrawler: ['Street Punk Brawler'],
  StreetPunkBlade: ['Street Punk Blade'],
  StreetPunkBullet: ['Street Punk Bullet'],
  StreetPunkNails: ['Street Punk Nails'],
  StreetPunkGatling: ['Street Punk Gatling'],
  Tilestone: ['Tilestone'],
  Camie: ['Camie'],
  Pappagu: ['Pappagu'],
  Doma: ['Doma'],
  DecalvanBrothers: ['Decalvan Brothers'],
  Squard: ['Squard'],
  WhiteyBay: ['Whitey Bay'],
  LittleOarsJr: ['Little Oars Jr.'],
  Duval: ['Duval'],
  NefertariCobra: ['Nefertari Cobra'],
  Koala: ['Koala'],
  Hack: ['Hack'],
  Inazuma: ['Inazuma'],
  Calgara: ['Calgara'],
  MontBlancNoland: ['Mont Blanc Noland'],
  HalberdCoporalNavy: ['Halberd Coporal Navy'],
  PistolCoporalNavy: ['Pistol Coporal Navy'],
  SaberCoporalNavy: ['Saber Coporal Navy'],
  BazookaCoporalNavy: ['Bazooka Coporal Navy'],
  KnuckleCoporalNavy: ['Knuckle Coporal Navy'],
  Oimo: ['Oimo'],
  Kashi: ['Kashi'],
  WatchdogUnitOfTheLaw: ['Watchdog Unit of the Law'],
  JustJuryman: ['Just Juryman'],
  ThreeHeadedBaskerville: ['Three-Headed Baskerville'],
  Blueno: ['Blueno'],
  Ganfor: ['Ganfor', 'Gan Fall'],
  Pierre: ['Pierre'],
  Conis: ['Conis'],
  Jerry: ['Jerry'],
  TBone: ['T-Bone'],
  Jabra: ['Jabra'],
  Fukuro: ['Fukuro'],
  Kumadori: ['Kumadori'],
  Spandam: ['Spandam'],
  Nero: ['Nero'],
  Wanze: ['Wanze'],
  Shirahoshi: ['Shirahoshi'],
  Dalmatian: ['Dalmatian'],
  Shu: ['Shu'],
  VeryGood: ['Very Good'],
  Strawberry: ['Strawberry'],
  LuckyRoux: ['Lucky Roux', 'Lucky Roo'],
  Genzo: ['Genzo'],
  Hiriluk: ['Hiriluk'],
  Kuina: ['Kuina'],
  UsoppPirates: ['Usopp Pirates'],
  Iceburg: ['Iceburg'],
  Breed: ['Breed'],
  OctopusBoxer: ['Octopus Boxer'],
  Lola: ['Lola'],
  RiskyBrothers: ['Risky Brothers'],
  Cerberus: ['Cerberus'],
  Tararan: ['Tararan'],
  BearSkinRug: ['Bear-Skin Rug'],
  SoldierZombie: ['Soldier Zombie'],
  WildZombie: ['Wild Zombie'],
  Mr7: ['Mr. 7'],
  MissFathersDay: ["Miss Father's Day"],
  CaesarClown: ['Caesar Clown'],
  Vergo: ['Vergo'],
  Monet: ['Monet'],
  Baby5: ['Baby 5'],
  Buffalo: ['Buffalo'],
  Tom: ['Tom'],
  Robson: ['Robson'],
  Sugar: ['Sugar'],
  SenorPink: ['Señor Pink'],
  Trebol: ['Trebol'],
  Giolla: ['Giolla'],
  LaoG: ['Lao G'],
  HoroHoroGhost: ['Horo Horo Ghost'],
  Oars: ['Oars'],
  Yokozuna: ['Yokozuna'],
  Marguerite: ['Marguerite'],
  Aphelandra: ['Aphelandra'],
  SweetPea: ['Sweet Pea'],
  Doberman: ['Doberman'],
  Hannyabal: ['Hannyabal'],
  Saldeath: ['Saldeath'],
  Blugori: ['Blugori'],
  Pica: ['Pica'],
  BenBeckman: ['Ben Beckman'],
  Gyaro: ['Gyaro'],
  Makuro: ['Makuro'],
  Tansui: ['Tansui'],
  GunmanQCK2: ['Gunman QCK 2'],
  GunmanINT: ['Gunman INT'],
  GunmanDEX: ['Gunman DEX'],
  GunmanQCK: ['Gunman QCK'],
  GunmanSTR: ['Gunman STR'],
  GunmanPSY: ['Gunman PSY'],
  Charloss: ['Charloss'],
  Roswald: ['Roswald'],
  Shalulia: ['Shalulia'],
  Pacifista: ['Pacifista'],
  Sentomaru: ['Sentomaru'],
  Borsalino: ['Borsalino', 'Kizaru'],
  DemaloBlack: ['Demalo Black'],
  Chocolat: ['Chocolat'],
  Cocoa: ['Cocoa'],
  NoraGitsune: ['Nora Gitsune'],
  Manjaro: ['Manjaro'],
  Drip: ['Drip'],
  Mounblutain: ['Mounblutain'],
  Turco: ['Turco'],
  Machvise: ['Machvise'],
  Gladius: ['Gladius'],
  Viola: ['Viola', 'Violet'],
  Dellinger: ['Dellinger'],
  Diamante: ['Diamante'],
  DonquixoteRosinante: ['Donquixote Rosinante', 'Corazon'],
  Sachi: ['Sachi'],
  Penguin: ['Penguin'],
  JeanBart: ['Jean Bart'],
  CountButler: ['Count Butler'],
  PresidentHeaby: ['President Heaby'],
  GeneralHotdog: ['General Hotdog'],
  Brownbeard: ['Brownbeard'],
  Chinjao: ['Chinjao'],
  BlueGilly: ['Blue Gilly'],
  FunkBrothers: ['Funk Brothers'],
  Hajrudin: ['Hajrudin'],
  Abdullah: ['Abdullah'],
  Jeet: ['Jeet'],
  Bartolomeo: ['Bartolomeo'],
  NicoOlvia: ['Nico Olvia'],
  Saul: ['Saul'],
  BoaSandersonia: ['Boa Sandersonia'],
  BoaMarigold: ['Boa Marigold'],
  Kikyo: ['Kikyo'],
  Gloriosa: ['Gloriosa', 'Elder Nyon'],
  FemaleArcherSTR: ['Female Archer STR'],
  FemaleArcherINT: ['Female Archer INT'],
  SwordswomanINT: ['Swordswoman INT'],
  SwordswomanPSY: ['Swordswoman PSY'],
  FemaleFighterDEX: ['Female Fighter DEX'],
  FemaleFighterQCK: ['Female Fighter QCK'],
  ShuraiyaBascud: ['Shuraiya Bascud'],
  Gasparde: ['Gasparde'],
  Needless: ['Needless'],
  RikuDoldoIII: ['Riku Doldo III', 'Ricky'],
  Leo: ['Leo'],
  Mansherry: ['Mansherry'],
  Kyros: ['Kyros', 'Toy Soldier'],
  Sai: ['Sai'],
  Issho: ['Issho', 'Fujitora'],
  Musshuru: ['Musshuru'],
  Saga: ['Saga'],
  Indigo: ['Indigo'],
  Scarlet: ['Scarlet'],
  Billy: ['Billy'],
  Binz: ['Binz'],
  Shiki: ['Shiki'],
  Cavendish: ['Cavendish'],
  Suleiman: ['Suleiman'],
  Orlumbus: ['Orlumbus'],
  Dagama: ['Dagama'],
  Elizabello: ['Elizabello II'],
  Ideo: ['Ideo'],
  UniformedGuardSTR: ['Uniformed Guard STR'],
  UniformedGuardQCK: ['Uniformed Guard QCK'],
  UniformedGuardDEX: ['Uniformed Guard DEX'],
  JailerINT: ['Jailer INT'],
  JailerPSY: ['Jailer PSY'],
  Minotaur: ['Minotaur'],
  Minozebra: ['Minozebra'],
  Sphinx: ['Sphinx'],
  ArmyWolf: ['Army Wolf'],
  Magellan: ['Magellan'],
  GildTesoro: ['Gild Tesoro'],
  Carina: ['Carina'],
  Baccarat: ['Baccarat'],
  Dice: ['Dice'],
  Tanaka: ['Tanaka'],
  Blenheim: ['Blenheim'],
  Kingdew: ['Kingdew'],
  Haruta: ['Haruta'],
  Atmos: ['Atmos'],
  SpeedJil: ['Speed Jil'],
  Yorki: ['Yorki'],
  Gairam: ['Gairam'],
  Sebastian: ['Sebastian'],
  Nightin: ['Nightin'],
  ByrnndiWorld: ['Byrnndi World'],
  Bastille: ['Bastille'],
  Yamakaji: ['Yamakaji'],
  Maynard: ['Maynard'],
  Laffitte: ['Laffitte'],
  VanAugur: ['Van Augur'],
  JesusBurgess: ['Jesus Burgess'],
  Shiryu: ['Shiryu'],
  DocQ: ['Doc Q'],
  JohnGiant: ['John Giant'],
  Sakazuki: ['Sakazuki', 'Akainu'],
  Kinemon: ["Kin'emon", 'Kinemon'],
  Wicca: ['Wicca'],
  Gancho: ['Gancho'],
  Cub: ['Cub', 'Kabu'],
  Bian: ['Bian'],
  KurozumiKanjuro: ['Kurozumi Kanjuro'],
  Dadan: ['Dadan'],
  Porchemy: ['Porchemy'],
  Bluejam: ['Bluejam'],
  TorinoKingdomMonsters: ['Torino Kingdom Monsters'],
  Humandrills: ['Humandrills'],
  Haredas: ['Haredas'],
  ThievesOfTehnaGehnaKingdom: ['Thieves of Tehna Gehna Kingdom'],
  TequilaWolfGuard: ['Tequila Wolf Guard'],
  Pekoms: ['Pekoms'],
  BaronTamago: ['Baron Tamago', 'Viscount Hiyoko', 'Count Niwatori'],
  Ronse: ['Ronse'],
  Stainless: ['Stainless'],
  Boo: ['Boo'],
  JeanAngo: ['Jean Ango'],
  HodyJones: ['Hody Jones'],
  Hyouzou: ['Hyouzou'],
  IkarosMuch: ['Ikaros Much'],
  Daruma: ['Daruma'],
  Zeo: ['Zeo'],
  Dosun: ['Dosun'],
  LipService: ['Lip Service'],
  Albion: ['Albion'],
  Neptune: ['Neptune'],
  Fukaboshi: ['Fukaboshi'],
  Caribou: ['Caribou'],
  VanderDeckenIX: ['Vander Decken IX'],
  Shyarly: ['Shyarly'],
  FishmanOutlawSTR: ['Fishman Outlaw STR'],
  FishmanOutlawQCK: ['Fishman Outlaw QCK'],
  FishmanOutlawDEX: ['Fishman Outlaw DEX'],
  BombardmentFishmanOutlawINT: ['Bombardment Fishman Outlaw INT'],
  BombardmentFishmanOutlawPSY: ['Bombardment Fishman Outlaw PSY'],
  FishmanGuardSTR: ['Fishman Guard STR'],
  FishmanGuardQCK: ['Fishman Guard QCK'],
  FishmanGuardDEX: ['Fishman Guard DEX'],
  Coribou: ['Coribou'],
  Hammond: ['Hammond'],
  Dogra: ['Dogra'],
  Wadatsumi: ['Wadatsumi'],
  Inuarashi: ['Inuarashi'],
  Wanda: ['Wanda'],
  Sicilian: ['Sicilian'],
  KozukiMomonosuke: ['Kozuki Momonosuke'],
  Ryuboshi: ['Ryuboshi'],
  Manboshi: ['Manboshi'],
  McGuy: ['McGuy'],
  FisherTiger: ['Fisher Tiger'],
  PunkHazardDragon: ['Punk Hazard Dragon'],
  Rock: ['Rock'],
  Scotch: ['Scotch'],
  GasMaskPatrolSTR: ['Gas Mask Patrol STR'],
  GasMaskPatrolQCK: ['Gas Mask Patrol QCK'],
  GasMaskPatrolDEX: ['Gas Mask Patrol DEX'],
  GasMaskPatrolINT: ['Gas Mask Patrol INT'],
  GasMaskPatrolPSY: ['Gas Mask Patrol PSY'],
  PatrolTroopCorpsSTR: ['Patrol Troop Corps STR'],
  PatrolTroopCorpsQCK: ['Patrol Troop Corps QCK'],
  PatrolTroopCorpsDEX: ['Patrol Troop Corps DEX'],
  Nekomamushi: ['Nekomamushi', 'Cat'],
  Pedro: ['Pedro'],
  Carrot: ['Carrot'],
  Raizo: ['Raizo'],
  Heat: ['Heat'],
  Wire: ['Wire'],
  VegapunksDragon: ["Vegapunk's Dragon"],
  FightingFish: ['Fighting Fish'],
  Spartan: ['Spartan'],
  DonquixotePiratesMemberSTR: ['Donquixote Pirates Member STR'],
  DonquixotePiratesMemberQCK: ['Donquixote Pirates Member QCK'],
  DonquixotePiratesMemberDEX: ['Donquixote Pirates Member DEX'],
  DonquixotePiratesMemberINT: ['Donquixote Pirates Member INT'],
  DonquixotePiratesMemberPSY: ['Donquixote Pirates Member PSY'],
  PrincessScarlet: ['Princess Scarlet'],
  TankLepanto: ['Tank Lepanto'],
  VinsmokeJudge: ['Vinsmoke Judge'],
  VinsmokeReiju: ['Vinsmoke Reiju'],
  VinsmokeIchiji: ['Vinsmoke Ichiji'],
  VinsmokeNiji: ['Vinsmoke Niji'],
  VinsmokeYonji: ['Vinsmoke Yonji'],
  CharlottePudding: ['Charlotte Pudding'],
  Makino: ['Makino'],
  Brannew: ['Brannew'],
  Yasopp: ['Yasopp'],
  Headcracker: ['Headcracker'],
  Kyuin: ['Kyuin'],
  CharlotteLinlin: ['Charlotte Linlin', 'Big Mom'],
  CharlotteKatakuri: ['Charlotte Katakuri'],
  CharlotteBrulee: ['Charlotte Brûlée'],
  CharlotteAmande: ['Charlotte Amande'],
  Bobbin: ['Bobbin'],
  CharlotteOven: ['Charlotte Oven'],
  Randolph: ['Randolph'],
  NobleCroc: ['Noble Croc'],
  Diesel: ['Diesel'],
  CharlotteCracker: ['Charlotte Cracker'],
  CharlotteOpera: ['Charlotte Opera'],
  Jack: ['Jack'],
  Roddy: ['Roddy'],
  Blackback: ['Blackback'],
  Miyagi: ['Miyagi'],
  Tristan: ['Tristan'],
  Guardians: ['Guardians'],
  Musketeers: ['Musketeers'],
  Gifters: ['Gifters'],
  Pleasures: ['Pleasures'],
  Sheepshead: ['Sheepshead'],
  CharlotteSmoothie: ['Charlotte Smoothie'],
  CharlottePerospero: ['Charlotte Perospero'],
  CharlotteDaifuku: ['Charlotte Daifuku'],
  Pound: ['Pound'],
  KingBaum: ['King Baum'],
  Homies: ['Homies'],
  Aladdin: ['Aladdin'],
  CharlottePraline: ['Charlotte Praline'],
  CharlotteChiffon: ['Charlotte Chiffon'],
  Vito: ['Vito'],
  Gotti: ['Gotti'],
  GermaSoldierSTR: ['Germa Soldier STR'],
  GermaSoldierDEX: ['Germa Soldier DEX'],
  GermaSoldierQCK: ['Germa Soldier QCK'],
  SeaAnt: ['Sea Ant'],
  NegativeHomie: ['Negative Homie'],
  PositiveHomie: ['Positive Homie'],
  Stussy: ['Stussy'],
  CharlotteBavarois: ['Charlotte Bavarois'],
  CharlotteGalette: ['Charlotte Galette'],
  CharlotteCompote: ['Charlotte Compote'],
  CharlotteMascarpone: ['Charlotte Mascarpone'],
  CharlotteJoscarpone: ['Charlotte Joscarpone'],
  CharlotteFlampe: ['Charlotte Flampe'],
  CharlotteMontdOr: ["Charlotte Mont-d'Or", 'Charlotte Montdor'],
  Streusen: ['Streusen'],
  MotherCaramel: ['Mother Caramel'],
  Kaido: ['Kaido'],
  VinsmokeSora: ['Vinsmoke Sora'],
  Koshiro: ['Koshiro'],
  AO: ['A.O.'],
  EdwardWeevil: ['Edward Weevil'],
  Zeus: ['Zeus'],
  Prometheus: ['Prometheus'],
  Rockstar: ['Rockstar'],
  Lindbergh: ['Lindbergh'],
  BeloBetty: ['Belo Betty'],
  Karasu: ['Karasu'],
  Morley: ['Morley'],
  DonquixoteHoming: ['Donquixote Homing'],
  SaintMjosgard: ['Saint Mjosgard'],
  PawnSTR: ['Pawn STR'],
  PawnDEX: ['Pawn DEX'],
  RookSTR: ['Rook STR'],
  RookDEX: ['Rook DEX'],
  KingPSY: ['King PSY'],
  KingINT: ['King INT'],
  DouglasBullet: ['Douglas Bullet'],
  Ann: ['Ann'],
  DonaldModerate: ['Donald Moderate'],
  Holdem: ['Holdem'],
  Speed: ['Speed'],
  CharlottePoire: ['Charlotte Poire'],
  KozukiHiyori: ['Kozuki Hiyori', 'Komurasaki'],
  Kikunojo: ['Kikunojo'],
  Tama: ['Tama'],
  MissTsuru: ['Miss Tsuru'],
  Denjiro: ['Denjiro', 'Kyoshiro'],
  AshuraDoji: ['Ashura Doji', 'Shutenmaru'],
  TenguyamaHitetsu: ['Tenguyama Hitetsu'],
  CharlotteCustard: ['Charlotte Custard'],
  Unluckies: ['Unluckies'],
  BuenaFesta: ['Buena Festa'],
  PageOne: ['Page One', 'Pay Pay'],
  Toko: ['Toko'],
  King: ['King'],
  Onimaru: ['Onimaru'],
  Gyukimaru: ['Gyukimaru', 'Onimaru'],
  KurozumiOrochi: ['Kurozumi Orochi'],
  Queen: ['Queen'],
  Shinobu: ['Shinobu'],
  Hyogoro: ['Hyogoro'],
  Dobon: ['Dobon'],
  KozukiOden: ['Kozuki Oden'],
  GolDRoger: ['Gol D. Roger'],
  MariejoisGuard: ['Mariejois Guard'],
  Peachbeard: ['Peachbeard'],
  Stelly: ['Stelly'],
  CaponePez: ['Capone Pez'],
  Kawamatsu: ['Kawamatsu'],
  AvaloPizarro: ['Avalo Pizarro'],
  CatarinaDevon: ['Catarina Devon'],
  VascoShot: ['Vasco Shot'],
  SanjuanWolf: ['Sanjuan Wolf'],
  Condoriano: ['Condoriano'],
  KozukiToki: ['Kozuki Toki'],
  ScopperGaban: ['Scopper Gaban'],
  Morgans: ['Morgans'],
  Yamato: ['Yamato'],
  Sasaki: ['Sasaki'],
  Ulti: ['Ulti'],
  BlackMaria: ['Black Maria'],
  WhosWho: ["Who's Who", 'Whos Who'],
  EvolverPenguin: ['Evolver Penguin'],
  Crab: ['Crab'],
  StripedDragon: ['Striped Dragon'],
  Turtle: ['Turtle'],
  SeaHorse: ['Sea Horse'],
  JeweledPorc: ['Jeweled Porc'],
  Concelot: [ "Concelot" ],
  Giovanni: [ "Giovanni" ],
}
